global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'travel-agency-command-side'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['travel-agency-command-side:8080']

  - job_name: 'travel-agency-query-side'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['travel-agency-query-side:8081']
